package com.mrmusic.fin.ui.theme

import android.content.Context
import androidx.compose.ui.graphics.Color

/**
 * The visual theme catalogue. A theme is an *aesthetic* — accent hue, surface
 * tints, bubble colours — layered on top of the light / dark decision, which
 * stays with the existing System / Light / Dark picker. Every theme therefore
 * ships a light AND a dark variant, so "Crystal" reads icy-white in light mode
 * and deep-teal in dark mode, and switching the OS appearance never changes
 * the theme the user chose.
 *
 * Persistence: `appearance_prefs` / [KEY_APP_THEME] as the [id] string (not an
 * index) so adding or reordering themes never silently changes a user's pick.
 * The same string tokens are exposed to the agent as `appearance.app_theme`
 * via the config registry.
 *
 * Adding a theme = add an enum case + one [ThemeVariant] per mode + a label
 * string. Nothing else needs to change.
 */
enum class AppTheme(
    val id: String,
    val light: ThemeVariant,
    val dark: ThemeVariant,
) {
    /** The stock look — neutral grouped surfaces with the desaturated iOS blue accent. */
    DEFAULT(
        id = "default",
        light = ThemeVariant(
            primary = Color(0xFF528AD2),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD6E3F7),
            onPrimaryContainer = Color(0xFF0B2A52),
            secondary = Color(0xFF4A6360),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCCE8E4),
            onSecondaryContainer = Color(0xFF05201D),
            tertiary = Color(0xFF46617A),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFCDE5FF),
            onTertiaryContainer = Color(0xFF001D32),
            background = Color(0xFFF2F2F7),
            onBackground = Color(0xFF171D1C),
            card = Color(0xFFFFFFFF),
            cardElevated = Color(0xFFF7F7FA),
            onSurfaceVariant = Color(0xFF3F4947),
            outline = Color(0xFFD1D1D6),
            chatBackground = Color.White,
            userBubble = Color(0x1E787880),
            fabAccent = Color(0xFFB7AF96),
            link = Color(0xFF007AFF),
            thinking = Color(0xFF007AFF),
            codeBlockBg = Color(0xFF000000),
            codeBlockText = Color(0xFF34C759),
            inlineCodeText = Color(0xFFFF9500),
            swatch = listOf(Color(0xFFF2F2F7), Color(0xFF528AD2), Color(0xFFFFFFFF)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFF6A94CE),
            onPrimary = Color(0xFF002A57),
            primaryContainer = Color(0xFF1F3F6B),
            onPrimaryContainer = Color(0xFFD6E3F7),
            secondary = Color(0xFFB1CCC8),
            onSecondary = Color(0xFF1C3532),
            secondaryContainer = Color(0xFF334B48),
            onSecondaryContainer = Color(0xFFCCE8E4),
            tertiary = Color(0xFFADC9E6),
            onTertiary = Color(0xFF15334A),
            tertiaryContainer = Color(0xFF2E4A61),
            onTertiaryContainer = Color(0xFFCDE5FF),
            background = Color(0xFF000000),
            onBackground = Color(0xFFDEE4E2),
            card = Color(0xFF1C1C1E),
            cardElevated = Color(0xFF2C2C2E),
            onSurfaceVariant = Color(0xFFBEC9C6),
            outline = Color(0xFF38383A),
            chatBackground = Color(0xFF000000),
            userBubble = Color(0xFF2F3A5C),
            fabAccent = Color(0xFF504C42),
            link = Color(0xFF0A84FF),
            thinking = Color(0xFF0A84FF),
            codeBlockBg = Color(0xFF262626),
            codeBlockText = Color(0xFF8CF38C),
            inlineCodeText = Color(0xFFFF9F0A),
            swatch = listOf(Color(0xFF000000), Color(0xFF6A94CE), Color(0xFF1C1C1E)),
        ),
    ),

    /** Deep indigo void, nebula-violet accent, starlight text. */
    SPACE(
        id = "space",
        light = ThemeVariant(
            primary = Color(0xFF5B4FCF),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFE3DFFF),
            onPrimaryContainer = Color(0xFF150066),
            secondary = Color(0xFF5E5C71),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE4DFF9),
            onSecondaryContainer = Color(0xFF1B192C),
            tertiary = Color(0xFF7A5375),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD6FA),
            onTertiaryContainer = Color(0xFF2F112E),
            background = Color(0xFFEEEDF7),
            onBackground = Color(0xFF1B1B2B),
            card = Color(0xFFFFFFFF),
            cardElevated = Color(0xFFF4F2FF),
            onSurfaceVariant = Color(0xFF474554),
            outline = Color(0xFFCAC6DC),
            chatBackground = Color(0xFFF7F6FD),
            userBubble = Color(0x2E5B4FCF),
            fabAccent = Color(0xFF7B70E0),
            link = Color(0xFF5B4FCF),
            thinking = Color(0xFF7A5375),
            codeBlockBg = Color(0xFF0E0B2A),
            codeBlockText = Color(0xFFB6ABFF),
            inlineCodeText = Color(0xFF8E3ED6),
            swatch = listOf(Color(0xFFEEEDF7), Color(0xFF5B4FCF), Color(0xFFFFD6FA)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFFA89CFF),
            onPrimary = Color(0xFF1E0A7A),
            primaryContainer = Color(0xFF3A2FA0),
            onPrimaryContainer = Color(0xFFE3DFFF),
            secondary = Color(0xFFC8C3DD),
            onSecondary = Color(0xFF302E42),
            secondaryContainer = Color(0xFF464459),
            onSecondaryContainer = Color(0xFFE4DFF9),
            tertiary = Color(0xFFEAB9E1),
            onTertiary = Color(0xFF472545),
            tertiaryContainer = Color(0xFF603B5C),
            onTertiaryContainer = Color(0xFFFFD6FA),
            background = Color(0xFF05041A),
            onBackground = Color(0xFFE6E3F5),
            card = Color(0xFF14122E),
            cardElevated = Color(0xFF1F1C40),
            onSurfaceVariant = Color(0xFFC9C5DC),
            outline = Color(0xFF3A3757),
            chatBackground = Color(0xFF05041A),
            userBubble = Color(0xFF2B2670),
            fabAccent = Color(0xFF4D43B3),
            link = Color(0xFFB8AEFF),
            thinking = Color(0xFFEAB9E1),
            codeBlockBg = Color(0xFF0E0C28),
            codeBlockText = Color(0xFFB6ABFF),
            inlineCodeText = Color(0xFFFFB2F4),
            swatch = listOf(Color(0xFF05041A), Color(0xFFA89CFF), Color(0xFF2B2670)),
        ),
    ),

    /** Warm daylight — amber accent on cream, ember on charcoal after dark. */
    SUN(
        id = "sun",
        light = ThemeVariant(
            primary = Color(0xFFD9822B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDCC2),
            onPrimaryContainer = Color(0xFF3A1B00),
            secondary = Color(0xFF745944),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDCC2),
            onSecondaryContainer = Color(0xFF2B1707),
            tertiary = Color(0xFF5F6134),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFE5E6AD),
            onTertiaryContainer = Color(0xFF1C1D00),
            background = Color(0xFFFBF3E7),
            onBackground = Color(0xFF241A10),
            card = Color(0xFFFFFCF6),
            cardElevated = Color(0xFFFFF4E6),
            onSurfaceVariant = Color(0xFF574335),
            outline = Color(0xFFE6D5C3),
            chatBackground = Color(0xFFFFFBF4),
            userBubble = Color(0x33D9822B),
            fabAccent = Color(0xFFE39A4D),
            link = Color(0xFFC96A00),
            thinking = Color(0xFFD9822B),
            codeBlockBg = Color(0xFF2B1D0E),
            codeBlockText = Color(0xFFFFC978),
            inlineCodeText = Color(0xFFB5541C),
            swatch = listOf(Color(0xFFFBF3E7), Color(0xFFD9822B), Color(0xFFFFDCC2)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFFFFB86B),
            onPrimary = Color(0xFF4A2600),
            primaryContainer = Color(0xFF6B3A00),
            onPrimaryContainer = Color(0xFFFFDCC2),
            secondary = Color(0xFFE3C0A6),
            onSecondary = Color(0xFF422C1A),
            secondaryContainer = Color(0xFF5B422E),
            onSecondaryContainer = Color(0xFFFFDCC2),
            tertiary = Color(0xFFC8CA93),
            onTertiary = Color(0xFF31330A),
            tertiaryContainer = Color(0xFF474A1F),
            onTertiaryContainer = Color(0xFFE5E6AD),
            background = Color(0xFF140E08),
            onBackground = Color(0xFFF2E6D9),
            card = Color(0xFF241A11),
            cardElevated = Color(0xFF32261A),
            onSurfaceVariant = Color(0xFFDCC5B2),
            outline = Color(0xFF4A3A2B),
            chatBackground = Color(0xFF140E08),
            userBubble = Color(0xFF5A3A16),
            fabAccent = Color(0xFF8A5A20),
            link = Color(0xFFFFB86B),
            thinking = Color(0xFFFFC978),
            codeBlockBg = Color(0xFF221810),
            codeBlockText = Color(0xFFFFC978),
            inlineCodeText = Color(0xFFFFA24C),
            swatch = listOf(Color(0xFF140E08), Color(0xFFFFB86B), Color(0xFF5A3A16)),
        ),
    ),

    /** Cool silver-blue, hushed and low-contrast — moonlit slate at night. */
    MOON(
        id = "moon",
        light = ThemeVariant(
            primary = Color(0xFF546A8A),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD7E3FA),
            onPrimaryContainer = Color(0xFF0F1F36),
            secondary = Color(0xFF5B6473),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFDFE6F4),
            onSecondaryContainer = Color(0xFF18202D),
            tertiary = Color(0xFF6F5F86),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFEFDFFF),
            onTertiaryContainer = Color(0xFF291C3E),
            background = Color(0xFFEEF1F6),
            onBackground = Color(0xFF1B1F27),
            card = Color(0xFFFAFBFE),
            cardElevated = Color(0xFFF1F4FA),
            onSurfaceVariant = Color(0xFF444A56),
            outline = Color(0xFFCBD2DE),
            chatBackground = Color(0xFFF6F8FC),
            userBubble = Color(0x2E546A8A),
            fabAccent = Color(0xFF8A9BB8),
            link = Color(0xFF3F5B85),
            thinking = Color(0xFF6F5F86),
            codeBlockBg = Color(0xFF1A2130),
            codeBlockText = Color(0xFFBFD3F5),
            inlineCodeText = Color(0xFF4F6C97),
            swatch = listOf(Color(0xFFEEF1F6), Color(0xFF546A8A), Color(0xFFD7E3FA)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFFB8CBEA),
            onPrimary = Color(0xFF223650),
            primaryContainer = Color(0xFF3A4E6C),
            onPrimaryContainer = Color(0xFFD7E3FA),
            secondary = Color(0xFFC2CAD8),
            onSecondary = Color(0xFF2D3441),
            secondaryContainer = Color(0xFF434B59),
            onSecondaryContainer = Color(0xFFDFE6F4),
            tertiary = Color(0xFFD5C4EE),
            onTertiary = Color(0xFF3B2E51),
            tertiaryContainer = Color(0xFF53456A),
            onTertiaryContainer = Color(0xFFEFDFFF),
            background = Color(0xFF0B0E14),
            onBackground = Color(0xFFDDE2EB),
            card = Color(0xFF171B24),
            cardElevated = Color(0xFF222733),
            onSurfaceVariant = Color(0xFFC0C7D3),
            outline = Color(0xFF353C4A),
            chatBackground = Color(0xFF0B0E14),
            userBubble = Color(0xFF2C3A55),
            fabAccent = Color(0xFF4D5D7A),
            link = Color(0xFFB8CBEA),
            thinking = Color(0xFFD5C4EE),
            codeBlockBg = Color(0xFF141924),
            codeBlockText = Color(0xFFBFD3F5),
            inlineCodeText = Color(0xFFA9BEE6),
            swatch = listOf(Color(0xFF0B0E14), Color(0xFFB8CBEA), Color(0xFF2C3A55)),
        ),
    ),

    /** Crimson scales and gold — smouldering ember-red on charcoal after dark. */
    DRAGON(
        id = "dragon",
        light = ThemeVariant(
            primary = Color(0xFFB4262E),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDAD7),
            onPrimaryContainer = Color(0xFF410006),
            secondary = Color(0xFF7A5300),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFDF9E),
            onSecondaryContainer = Color(0xFF261900),
            tertiary = Color(0xFF6D5E00),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFBE375),
            onTertiaryContainer = Color(0xFF211B00),
            background = Color(0xFFF8F0EE),
            onBackground = Color(0xFF241716),
            card = Color(0xFFFFFBFA),
            cardElevated = Color(0xFFFCEFEC),
            onSurfaceVariant = Color(0xFF574140),
            outline = Color(0xFFE3CFCC),
            chatBackground = Color(0xFFFEF8F6),
            userBubble = Color(0x33B4262E),
            fabAccent = Color(0xFFC9A227),
            link = Color(0xFFA1141C),
            thinking = Color(0xFF9A6E00),
            codeBlockBg = Color(0xFF250B0C),
            codeBlockText = Color(0xFFFFB4AB),
            inlineCodeText = Color(0xFFB4262E),
            swatch = listOf(Color(0xFFF8F0EE), Color(0xFFB4262E), Color(0xFFFFDF9E)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFFFF7A6E),
            onPrimary = Color(0xFF690008),
            primaryContainer = Color(0xFF8E1219),
            onPrimaryContainer = Color(0xFFFFDAD7),
            secondary = Color(0xFFF2C14E),
            onSecondary = Color(0xFF402D00),
            secondaryContainer = Color(0xFF5C3F00),
            onSecondaryContainer = Color(0xFFFFDF9E),
            tertiary = Color(0xFFE6CF5A),
            onTertiary = Color(0xFF383000),
            tertiaryContainer = Color(0xFF524600),
            onTertiaryContainer = Color(0xFFFBE375),
            background = Color(0xFF120909),
            onBackground = Color(0xFFF1DEDC),
            card = Color(0xFF221213),
            cardElevated = Color(0xFF301B1C),
            onSurfaceVariant = Color(0xFFDDC0BD),
            outline = Color(0xFF4A3435),
            chatBackground = Color(0xFF120909),
            userBubble = Color(0xFF5E1E22),
            fabAccent = Color(0xFF8A6A12),
            link = Color(0xFFFF9B90),
            thinking = Color(0xFFF2C14E),
            codeBlockBg = Color(0xFF1E0F10),
            codeBlockText = Color(0xFFFFB4AB),
            inlineCodeText = Color(0xFFF2C14E),
            swatch = listOf(Color(0xFF120909), Color(0xFFFF7A6E), Color(0xFFF2C14E)),
        ),
    ),

    /** Icy aquamarine and frosted glass — deep glacial teal at night. */
    CRYSTAL(
        id = "crystal",
        light = ThemeVariant(
            primary = Color(0xFF0B8A8F),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFBDEFF1),
            onPrimaryContainer = Color(0xFF00201F),
            secondary = Color(0xFF4A6364),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCCE8E8),
            onSecondaryContainer = Color(0xFF051F20),
            tertiary = Color(0xFF4B607C),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD3E4FF),
            onTertiaryContainer = Color(0xFF041C35),
            background = Color(0xFFEDF6F7),
            onBackground = Color(0xFF161D1E),
            card = Color(0xFFFFFFFF),
            cardElevated = Color(0xFFF1FAFB),
            onSurfaceVariant = Color(0xFF3F4949),
            outline = Color(0xFFC6DADB),
            chatBackground = Color(0xFFF6FCFD),
            userBubble = Color(0x2E0B8A8F),
            fabAccent = Color(0xFF6FC5C9),
            link = Color(0xFF00767B),
            thinking = Color(0xFF4B607C),
            codeBlockBg = Color(0xFF0A2224),
            codeBlockText = Color(0xFF8FE3E6),
            inlineCodeText = Color(0xFF0B8A8F),
            swatch = listOf(Color(0xFFEDF6F7), Color(0xFF0B8A8F), Color(0xFFBDEFF1)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFF7FDCDF),
            onPrimary = Color(0xFF003738),
            primaryContainer = Color(0xFF005052),
            onPrimaryContainer = Color(0xFFBDEFF1),
            secondary = Color(0xFFB1CCCC),
            onSecondary = Color(0xFF1C3536),
            secondaryContainer = Color(0xFF334B4C),
            onSecondaryContainer = Color(0xFFCCE8E8),
            tertiary = Color(0xFFB3C8E8),
            onTertiary = Color(0xFF1D324B),
            tertiaryContainer = Color(0xFF344863),
            onTertiaryContainer = Color(0xFFD3E4FF),
            background = Color(0xFF061416),
            onBackground = Color(0xFFDCE6E7),
            card = Color(0xFF102224),
            cardElevated = Color(0xFF183032),
            onSurfaceVariant = Color(0xFFBEC9C9),
            outline = Color(0xFF2E4446),
            chatBackground = Color(0xFF061416),
            userBubble = Color(0xFF1B4A4D),
            fabAccent = Color(0xFF2E7376),
            link = Color(0xFF8FE3E6),
            thinking = Color(0xFFB3C8E8),
            codeBlockBg = Color(0xFF0C1E20),
            codeBlockText = Color(0xFF8FE3E6),
            inlineCodeText = Color(0xFF7FDCDF),
            swatch = listOf(Color(0xFF061416), Color(0xFF7FDCDF), Color(0xFF1B4A4D)),
        ),
    ),

    /** Moss and fern — sunlit canopy by day, deep-woods green after dark. */
    FOREST(
        id = "forest",
        light = ThemeVariant(
            primary = Color(0xFF3B7D4A),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFC3EFC8),
            onPrimaryContainer = Color(0xFF00210A),
            secondary = Color(0xFF52634F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD5E8CF),
            onSecondaryContainer = Color(0xFF101F10),
            tertiary = Color(0xFF6B5E36),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFF3E1AE),
            onTertiaryContainer = Color(0xFF231B00),
            background = Color(0xFFEFF4EC),
            onBackground = Color(0xFF191D18),
            card = Color(0xFFFCFDFA),
            cardElevated = Color(0xFFF1F6EE),
            onSurfaceVariant = Color(0xFF424940),
            outline = Color(0xFFCCD6C8),
            chatBackground = Color(0xFFF7FAF5),
            userBubble = Color(0x2E3B7D4A),
            fabAccent = Color(0xFF8FB08A),
            link = Color(0xFF2C6B3B),
            thinking = Color(0xFF6B5E36),
            codeBlockBg = Color(0xFF0F1F12),
            codeBlockText = Color(0xFFA8E5AD),
            inlineCodeText = Color(0xFF3B7D4A),
            swatch = listOf(Color(0xFFEFF4EC), Color(0xFF3B7D4A), Color(0xFFF3E1AE)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFF9DD8A3),
            onPrimary = Color(0xFF07391A),
            primaryContainer = Color(0xFF22532F),
            onPrimaryContainer = Color(0xFFC3EFC8),
            secondary = Color(0xFFB9CCB3),
            onSecondary = Color(0xFF243424),
            secondaryContainer = Color(0xFF3A4B39),
            onSecondaryContainer = Color(0xFFD5E8CF),
            tertiary = Color(0xFFD7C594),
            onTertiary = Color(0xFF3A300B),
            tertiaryContainer = Color(0xFF524620),
            onTertiaryContainer = Color(0xFFF3E1AE),
            background = Color(0xFF0A120B),
            onBackground = Color(0xFFDFE5DC),
            card = Color(0xFF152017),
            cardElevated = Color(0xFF1F2D21),
            onSurfaceVariant = Color(0xFFC1CABD),
            outline = Color(0xFF33423A),
            chatBackground = Color(0xFF0A120B),
            userBubble = Color(0xFF244A2E),
            fabAccent = Color(0xFF3F6B47),
            link = Color(0xFFA8E5AD),
            thinking = Color(0xFFD7C594),
            codeBlockBg = Color(0xFF101C12),
            codeBlockText = Color(0xFFA8E5AD),
            inlineCodeText = Color(0xFF9DD8A3),
            swatch = listOf(Color(0xFF0A120B), Color(0xFF9DD8A3), Color(0xFF244A2E)),
        ),
    ),

    /** Abyssal navy and bioluminescent cyan — surf-foam and sea-glass by day. */
    OCEAN(
        id = "ocean",
        light = ThemeVariant(
            primary = Color(0xFF0E6FB8),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD2E6FF),
            onPrimaryContainer = Color(0xFF001C36),
            secondary = Color(0xFF4F6070),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD3E5F6),
            onSecondaryContainer = Color(0xFF0B1D2A),
            tertiary = Color(0xFF00696B),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF9CF1F2),
            onTertiaryContainer = Color(0xFF002020),
            background = Color(0xFFECF3FA),
            onBackground = Color(0xFF161C22),
            card = Color(0xFFFCFDFF),
            cardElevated = Color(0xFFF0F5FC),
            onSurfaceVariant = Color(0xFF41474E),
            outline = Color(0xFFC8D5E3),
            chatBackground = Color(0xFFF5F9FE),
            userBubble = Color(0x2E0E6FB8),
            fabAccent = Color(0xFF6AA9DE),
            link = Color(0xFF005DA1),
            thinking = Color(0xFF00696B),
            codeBlockBg = Color(0xFF071A2B),
            codeBlockText = Color(0xFF8FD3FF),
            inlineCodeText = Color(0xFF0E6FB8),
            swatch = listOf(Color(0xFFECF3FA), Color(0xFF0E6FB8), Color(0xFF9CF1F2)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFF7CC4FF),
            onPrimary = Color(0xFF003259),
            primaryContainer = Color(0xFF004A7F),
            onPrimaryContainer = Color(0xFFD2E6FF),
            secondary = Color(0xFFB8C8DA),
            onSecondary = Color(0xFF223240),
            secondaryContainer = Color(0xFF394957),
            onSecondaryContainer = Color(0xFFD3E5F6),
            tertiary = Color(0xFF80D4D6),
            onTertiary = Color(0xFF003738),
            tertiaryContainer = Color(0xFF004F51),
            onTertiaryContainer = Color(0xFF9CF1F2),
            background = Color(0xFF040D18),
            onBackground = Color(0xFFDCE3EC),
            card = Color(0xFF0E1B2A),
            cardElevated = Color(0xFF17283B),
            onSurfaceVariant = Color(0xFFC0C8D2),
            outline = Color(0xFF2B3D51),
            chatBackground = Color(0xFF040D18),
            userBubble = Color(0xFF184064),
            fabAccent = Color(0xFF2A6796),
            link = Color(0xFF8FD3FF),
            thinking = Color(0xFF80D4D6),
            codeBlockBg = Color(0xFF0A1826),
            codeBlockText = Color(0xFF8FD3FF),
            inlineCodeText = Color(0xFF7CC4FF),
            swatch = listOf(Color(0xFF040D18), Color(0xFF7CC4FF), Color(0xFF184064)),
        ),
    ),

    /** Cherry-blossom pink and plum — soft petals by day, dusk-magenta at night. */
    SAKURA(
        id = "sakura",
        light = ThemeVariant(
            primary = Color(0xFFC2416F),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFD9E2),
            onPrimaryContainer = Color(0xFF3F0020),
            secondary = Color(0xFF745660),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD9E2),
            onSecondaryContainer = Color(0xFF2B151D),
            tertiary = Color(0xFF7B5733),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDCC0),
            onTertiaryContainer = Color(0xFF2D1600),
            background = Color(0xFFFAF0F3),
            onBackground = Color(0xFF22191C),
            card = Color(0xFFFFFBFC),
            cardElevated = Color(0xFFFDEFF3),
            onSurfaceVariant = Color(0xFF524345),
            outline = Color(0xFFE8D0D6),
            chatBackground = Color(0xFFFEF7F9),
            userBubble = Color(0x33C2416F),
            fabAccent = Color(0xFFE79AB5),
            link = Color(0xFFAD2E5C),
            thinking = Color(0xFF7B5733),
            codeBlockBg = Color(0xFF2A0F19),
            codeBlockText = Color(0xFFFFB1C8),
            inlineCodeText = Color(0xFFC2416F),
            swatch = listOf(Color(0xFFFAF0F3), Color(0xFFC2416F), Color(0xFFFFD9E2)),
        ),
        dark = ThemeVariant(
            primary = Color(0xFFFFB0C8),
            onPrimary = Color(0xFF5F1138),
            primaryContainer = Color(0xFF7D2A4F),
            onPrimaryContainer = Color(0xFFFFD9E2),
            secondary = Color(0xFFE2BDC7),
            onSecondary = Color(0xFF422932),
            secondaryContainer = Color(0xFF5A3F48),
            onSecondaryContainer = Color(0xFFFFD9E2),
            tertiary = Color(0xFFEEBE92),
            onTertiary = Color(0xFF462A0A),
            tertiaryContainer = Color(0xFF60401E),
            onTertiaryContainer = Color(0xFFFFDCC0),
            background = Color(0xFF15090E),
            onBackground = Color(0xFFF0DEE3),
            card = Color(0xFF24151B),
            cardElevated = Color(0xFF321E26),
            onSurfaceVariant = Color(0xFFD7C1C7),
            outline = Color(0xFF4A363E),
            chatBackground = Color(0xFF15090E),
            userBubble = Color(0xFF5C2A42),
            fabAccent = Color(0xFF8A4A65),
            link = Color(0xFFFFB0C8),
            thinking = Color(0xFFEEBE92),
            codeBlockBg = Color(0xFF20121A),
            codeBlockText = Color(0xFFFFB1C8),
            inlineCodeText = Color(0xFFFFB0C8),
            swatch = listOf(Color(0xFF15090E), Color(0xFFFFB0C8), Color(0xFF5C2A42)),
        ),
    );

    /** Resolve the variant for the current light / dark decision. */
    fun variant(darkTheme: Boolean): ThemeVariant = if (darkTheme) dark else light

    companion object {
        /** Preference key inside `appearance_prefs`. Value is [AppTheme.id]. */
        const val KEY_APP_THEME = "app_theme"

        /** Stable ids in display order — reused by the config registry enum. */
        val ids: List<String> get() = entries.map { it.id }

        fun fromId(id: String?): AppTheme = entries.firstOrNull { it.id == id } ?: DEFAULT

        /** Read the persisted choice (default [DEFAULT]) — safe to call off the main thread. */
        fun current(context: Context): AppTheme = fromId(
            context.getSharedPreferences("appearance_prefs", Context.MODE_PRIVATE)
                .getString(KEY_APP_THEME, null)
        )
    }
}

/**
 * One light-or-dark rendition of an [AppTheme]. Only the colours that give a
 * theme its character live here; everything else in [ChatPalette] /
 * `MaterialTheme.colorScheme` is derived from these plus the neutral base
 * palette for the mode (see `Theme.kt`).
 */
data class ThemeVariant(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    /** Grouped page background (settings, lists). */
    val background: Color,
    val onBackground: Color,
    /** Grouped card surface. */
    val card: Color,
    /** Elevated card / sheet surface. */
    val cardElevated: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    /** Chat canvas behind the message list. */
    val chatBackground: Color,
    /** User message bubble fill. */
    val userBubble: Color,
    /** New-chat FAB / accent chip. */
    val fabAccent: Color,
    val link: Color,
    val thinking: Color,
    val codeBlockBg: Color,
    val codeBlockText: Color,
    val inlineCodeText: Color,
    /** Three colours the theme picker paints as a preview swatch. */
    val swatch: List<Color>,
)
